version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - tools_network
    ports:
      - 80:80
    volumes:
      - nginx_conf:/etc/nginx/
      - nginx_html:/usr/share/nginx/html/

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    networks:
      - tools_network
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"




volumes:
  nginx_conf:
  nginx_html:
  jenkins_home:

networks:
  tools_network: